services:
  db:
    image: postgres:14.5
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - pgadmin_pg_nb

  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      MAX_LOGIN_ATTEMPTS: 100
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pgadmin_pg_nb
  
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile_nb
    restart: always
    user: root
    command: jupyter lab --allow-root --ip=0.0.0.0 --NotebookApp.token='docker' --NotebookApp.notebook_dir=/home/jovyan/work
    environment:
      JUPYTER_TOKEN: "docker"
      GRANT_SUDO: "yes"
    ports:
      - "38888:8888"
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - pgadmin_pg_nb

networks:
  pgadmin_pg_nb:

volumes:
  local_pgdata:
  pgadmin-data:
